-- Insert rows into table 'Juego' in schema '[dbo]'
INSERT INTO [dbo].[Juego]

VALUES
(
 'God of War',
  'Han pasado años desde que Kratos tomó su venganza contra los Dioses Olímpicos. Habiendo sobrevivido la pelea final contra su padre Zeus, Kratos vive ahora con su joven hijo Atreus en el mundo de los Dioses Nórdicos, una tierra hostil habitada por feroces monstruos y guerreros. Kratos deberá actuar como mentor y protector de su hijo, y tendrá que dominar la ira y enojo que tuvo durante muchos años y atar cabos sueltos.
  Las armas principales de Kratos durante todo el videojuego son un hacha llamada "Leviathan" y un escudo. El Leviathan se puede lanzar para golpear o congelar a ciertos rivales, y regresará a la mano del personaje al oprimir un botón. Mientras que el escudo se utiliza tanto para retener y contraatacar golpes como para atacar a los enemigos durante el combate. Esta vez los saltos y dobles saltos de Kratos son suspendidos para dejar lugar a la escalada como forma de exploración de este nuevo mundo. Otro aspecto novedoso en la jugabilidad es la posibilidad de que Atreus pueda subir de nivel en el transcurso del juego, lo cual hará que este aprenda nuevas habilidades que ayudarán a Kratos pero este personaje no será jugable. Atreus funcionará como una extensión de las habilidades del protagonista, y atacará a los enemigos con nuestras órdenes y al completar algunos combos. Él puede lanzar una lluvia de flechas cuando no está directamente en combate, capaces de aturdir a los oponentes. Además se incluyen jefes opcionales y Kratos puede aumentar su salud máxima como en anteriores juegos.Los dos protagonistas pueden cruzar lagos y ríos mediante el uso de botes. También hay un sistema de mejoras para poder optimizar las armas, armaduras y las habilidades de los personajes. Uno de los cambios más notorios en la jugabilidad es el de la cámara, que pasa de ser panorámica a ubicarse cerca de Kratos y libre como cualquier otro sandbox. Cory Barlog se ha referido a este cambio como el que se hiciera anteriormente en la franquicia de Resident Evil.',
 '2018-04-20','Accion, Aventura','PLayStation, Windows','godofwar.jpg'
),
(
 'Minecraft',
 'Minecraft es un juego de mundo abierto, y no tiene un fin claramente definido. Esto permite una gran libertad en cuanto a la elección de su forma de jugar. A pesar de ello, el juego posee un sistema que otorga logros por completar ciertas acciones. La cámara es en primera persona, aunque los jugadores tienen la posibilidad de cambiarla a una perspectiva de tercera persona en cualquier momento.

El juego se centra en la colocación y destrucción de bloques, siendo que este se compone de objetos tridimensionales cúbicos, colocados sobre un patrón de rejilla fija. Estos cubos o bloques representan principalmente distintos elementos de la naturaleza, como tierra, piedra, minerales, troncos, entre otros. Los jugadores son libres de desplazarse por su entorno y modificarlo mediante la creación, recolección y transporte de los bloques que componen al juego, los cuales solo pueden ser colocados respetando la rejilla fija del juego. Los jugadores crean «granjas», que son estructuras y mecanismos para conseguir un determinado material más fácil (por ejemplo una granja que genera oro automáticamente). En el juego se pueden encontrar estructuras especiales como aldeas, galerías mineras, templos marinos, pirámides y templos selváticos.',
 '2009-5-17','Sandbox','Windows, macOS, Linux Xbox, PlayStation, Movil, Nintendo','minecraft.webp'
),
(
    'Satisfactory',
    'El jugador asume el papel de un ingeniero que ha sido enviado al planeta con órdenes de "colonizarlo" mediante la construcción de un complejo de fábricas para FICSIT. El jugador puede elegir entre cuatro lugares de inicio: las praderas, el desierto rocoso, el desierto de las dunas o el bosque del norte. Esta elección afecta los recursos a los que el jugador tiene acceso al principio del juego y la cantidad de terreno llano disponible para construir fácilmente. Sin embargo, el jugador puede moverse a cualquier otra parte del mapa en cualquier momento. Después de aterrizar, el jugador debe recuperar la cápsula de aterrizaje en busca de piezas con las que construir el Hub, la ubicación principal desde la que se extenderá la mayoría de las demás construcciones.

Durante un breve tutorial, el jugador aprende a extraer y procesar minerales básicos como el hierro y el cobre. Con estos materiales, es posible construir una fábrica simple y comenzar a explorar el sistema "Tier". A partir de mayo de 2021, hay ocho niveles de este tipo en el juego, cada uno de los cuales otorga acceso a materiales y equipos cada vez más complejos y sofisticados. [4] Los niveles uno y dos se desbloquean después de completar el tutorial; los niveles subsiguientes se desbloquean entregando ciertas partes al Space Elevator.

A medida que el jugador desbloquea nuevos equipos, es posible automatizar tareas más complicadas. Los objetivos finales del juego son construir una fábrica completamente automatizada que pueda fabricar cualquier artículo sin requerir la intervención manual del jugador y entregar todas las partes requeridas del proyecto al Space Elevator. La maquinaria de nivel superior requiere más energía, por lo que el jugador debe investigar y construir sistemas de energía, incluidos generadores de carbón y combustible y, finalmente , plantas de energía nuclear .

La exploración y el combate son elementos secundarios del juego. El jugador debe luchar contra formas de vida alienígenas hostiles y conquistar entornos peligrosos para encontrar recursos valiosos en la naturaleza. Hay un número limitado de armas y vehículos disponibles para facilitar la exploración.',
    '2019-4-19','Sandbox, Simulador de fabrica','Windows','satisfactory.jpg'
),
(
    'League of Legends',
    'El juego consta de 3 modos actuales de juego en ejecución: La Grieta del Invocador, El Abismo de los Lamentos y Teamfight Tactics. Los jugadores compiten en partidas, que duran entre 15 y 50 minutos en promedio. En cada modo de juego, los equipos trabajan juntos para lograr una condición de victoria, normalmente destruyendo la estructura central (llamado Nexo) en la base del equipo enemigo después de pasar por alto una línea de estructuras defensivas llamadas Torretas. En todos los modos de juego, los jugadores controlan personajes llamados «campeones», elegidos o asignados en cada partida, que tienen un conjunto de habilidades únicas, con los cuales jugarán toda la partida hasta su conclusión. Desde febrero de 2022, hay 159 campeones disponibles, siendo la última añadida Renata Glasc, la Quimobaronesa.

Los campeones comienzan cada partida con un bajo nivel, y luego ganan experiencia en el transcurso de la partida para alcanzar un nivel máximo de 18, excepto en modos como URF, que pueden subir de nivel infinitamente. Ganar niveles de experiencia en las partidas permite a los jugadores desbloquear las habilidades especiales de su campeón y aumentarlas de varias maneras únicas para cada personaje. Si un campeón pierde toda su salud, es derrotado, pero es revivido automáticamente en su base una vez que pase el tiempo suficiente. Los campeones también comienzan cada partida con una cantidad baja de oro, y pueden ganar oro adicional durante todo la partida de varias maneras: matando a personajes no jugadores conocidos como súbditos y monstruos; matando o ayudando a matar campeones enemigos; destruyendo las estructuras enemigas; pasivamente a través del tiempo; y a través de interacciones con artículos únicos o habilidades de campeón. Este oro se puede gastar a lo largo de la partida para comprar artículos del juego que aumentan aún más las estadísticas de cada campeón (ataque, defensa, vida, etc.) y la jugabilidad en una variedad de formas. La experiencia del campeón, el oro ganado y los artículos comprados son específicos de cada partida y no se transfieren a partidas posteriores. Por lo tanto, todos los jugadores comienzan cada partida en relativa igualdad de condiciones con respecto a su equipo contrario.

A través de las partidas, los jugadores también obtienen recompensas que se aplican a su cuenta. Las cuentas de los jugadores comienzan en el nivel uno y progresan mediante la cantidad de partidas jugadas. El nivel de jugador es independiente del nivel de personaje; tanto una cuenta de nivel 30 como una de nivel 5 comenzarían en el nivel de personaje 1 al comienzo de una nueva partida. Desde 2009 hasta 2017, el nivel máximo de la cuenta fue 30, y a medida que los jugadores progresaban, desbloquearon contenido y habilidades adicionales. Este sistema fue rediseñado en noviembre de 2017, con la eliminación del límite de nivel 30 y la eliminación del sistema de Runas/Maestrías que otorgó bonos progresivos a los jugadores en función de su nivel de cuenta. Jugar partidas y subir de nivel proporciona "Esencia Azul" (llamada "Puntos de Influencia" (IP) de 2009 a 2017), una moneda que se puede usar en lugar de "dinero real" para acceder a ciertas características bloqueadas.

En las partidas de 5 vs. 5, pasados 15 minutos de partida, es posible realizar una rendición, pero la votación debe de ser unánime. Cualquier jugador puede iniciar la votación (tomándose como un voto a favor). Al minuto 20 el 80% del equipo debe estar de acuerdo (4 jugadores de 5). Si una petición de rendición ha sido rechazada se deben esperar 3 minutos para poder pedir otra; mientras que si la rendición ha sido aprobada, el nexo propio se auto destruye, acabando así la partida en una derrota.',
    '2009-10-27','MOBA','Windows','leagueoflegends.jpeg'
),
(
    'Smite',
    'SMITE es un videojuego de acción MOBA en tercera persona, creado y publicado por Hi-Rez Studios para Microsoft Windows, Xbox One, PlayStation 4 y Nintendo Switch. El juego se basa en dos equipos, cada uno formado por cinco dioses, enfrentados en un campo de batalla con la finalidad de destruir el titán enemigo situado en cada una de las bases. Cada jugador se pone en la piel de un dios de diferentes mitologías el cual posee distintos poderes y características. En el campo de batalla también se pueden encontrar personajes no controlados (súbditos) que proporcionan oro y experiencia.

El juego fue anunciado el 21 de abril de 2012 en el PAX East. La Beta cerrada comenzó el 31 de mayo de 2012 y la beta abierta el 24 de enero de 2013. El juego fue lanzado oficialmente el 25 de marzo de 2014. La versión para Xbox One fue lanzada el 19 de agosto de 2015. El juego alcanzó los 10 000 000 de jugadores el 24 de julio de 2015.4​ Y el 3 de junio de 2016 superó los 20 000 000 de jugadores. Actualmente se puede registrar desde la página oficial del juego y desde ahí descargarlo y jugar.',
    '2014-7-24','MOBA','Windows, Mac, Xbox One, PlayStation, Nintendo Switch','smite.png'
),
(
    'The Legend of Zelda: Breath of the Wild',
    'Diez mil años antes del comienzo del juego, Hyrule es una civilización avanzada que construyó cuatro enormes máquinas con formas de animales llamadas bestias divinas y una legión de guardianes para protegerse de Ganon. Cuando Ganon regresó, fue derrotado por una princesa con la ayuda de los cuatro campeones y un caballero.

Unos nueve mil novecientos años después, los habitantes de Hyrule se enteraron por medio de una profecía de que se avecinaba el «Gran Cataclismo». La princesa Zelda entrena para despertar su poder y sellar a Ganon, Link es elegido como el portador de la Espada Maestra, mientras que Daruk, Revali, Mipha y Urbosa son elegidos para pilotar a las bestias divinas. Sin embargo, Ganon ideó un plan para contrarrestar los intentos defensas, corrompiendo a todas las máquinas, matando a los campeones y diezmando al reino. Link queda gravemente herido en la batalla y es llevado a una cámara de resurrección conocida como el santuario de la vida, mientras que Zelda usa su magia para atrapar a Ganon.

Transcurren cien años y Link despierta sin memoria de la cámara en un reino posapocalíptico devastado, al salir del santuario conoce a un anciano que se revela a sí mismo como el espíritu del rey Rhoam. El rey le explica que Zelda ha estado en una batalla en el castillo de Hyrule y que su poder se está desvaneciendo, por lo que le ruega a Link que derrote a Ganon antes de que se libere y destruya el mundo.

Tras la petición del rey, Link emprende un viaje a través de todo Hyrule para recuperar sus memorias. Con la ayuda de las tribus del reino aborda las bestias divinas para derrotar a las manifestaciones de Ganon que derrotaron a los campeones cien años antes y liberar sus espíritus. Después de obtener la Espada Maestra, Link se dirige al castillo de Hyrule para derrotar a Ganon con la ayuda de las bestias divinas.',
    '2017-3-3','Accion, Aventura, ROL','Wii U, NintendoSwitch','zelda.jpg'
),
(
    'Hollow Knight',
    'Hollow Knight es un videojuego perteneciente al género metroidvania desarrollado y publicado por Team Cherry. El videojuego fue inicialmente lanzado para Microsoft Windows en febrero de 2017, y más tarde para macOS y Linux en abril de 2017.La adaptación para Nintendo Switch fue lanzada el 12 de junio de 2018. El desarrollo fue parcialmente financiado como un proyecto Kickstarter que obtuvo 57 000 dólares hasta finales de 2014. El juego fue lanzado en las consolas PlayStation 4 y Xbox One el 25 de septiembre de 2018.

El videojuego cuenta la historia del Caballero, en su búsqueda para descubrir los secretos del largamente abandonado reino de Hallownest, cuyas profundidades atraen a los aventureros y valientes con la promesa de tesoros o la respuesta a misterios antiguos.',
    '2017-2-24','Metroidvania','Nintendo Switch, Windows, Linux, Mac, PlayStation, Xbox','hollowknight.png'
),
(
    'Forza Horizon 5',
    'Forza Horizon 5 es un videojuego de carreras ambientado en un entorno de mundo abierto con sede en México. El juego tiene el mapa más grande de toda la serie Forza Horizon, siendo 50% más grande que Forza Horizon 4. El director creativo, Mike Brown, describió el mapa como uno de los mapas de Forza Horizon más diversos que el equipo ha construido. El mapa contiene áreas como un volcán activo de caldera, selvas y playas, y ciudades como Guanajuato. Los jugadores pueden explorar el mundo abierto libremente, aunque también pueden competir en carreras multijugador y completar el modo campaña. Tanto los coches que aparecen en el juego como el personaje del jugador se pueden personalizar ampliamente. El juego es el primero de la franquicia que admite el trazado de rayos en los coches (aunque solo está disponible en ForzaVista).

Presenta también un nuevo sistema meteorológico (clima local), en el que los jugadores pueden visitar un lado del mapa y pueden ver visiblemente una tormenta. Debido a que México es una nación tan vasta con un rango tan amplio de elevaciones, aparecerían múltiples climas en el juego aproximadamente al mismo tiempo. Las cuatro estaciones todavía existen, pero afectarían a los once biomas únicos alrededor del mapa. Por ejemplo, en la estación seca, aparecerán tormentas de polvo, mientras que las tormentas tropicales ocurren durante la temporada de tormentas de otoño. Otro detalle está en la selva, en la que ahora el ambiente reaccionaría al clima; un ejemplo de esto son las hojas volando por todas partes.

Una de las principales novedades es el Horizon Arcade. Consiste en una serie de minijuegos multijugador esparcidos por el mapa. Uno de estos minijuegos multijugador es "Piñata pop", donde el avión de carga del Horizon Festival deja caer piñatas. El objetivo es hacer estallar tantas piñatas como puedan con la ayuda de otros jugadores. También presenta el "EventLab", un conjunto de herramientas en el que los jugadores pueden crear juegos personalizados, carreras y más, según sus preferencias personales. Se introdujo una nueva función llamada "Forza Link". Según Brown, es un asistente de IA que rastrea el estado actual de los jugadores, ayudándolos a conectarse con otros jugadores en línea y jugar juntos. Forza Link también puede vincular los sistemas GPS de los jugadores si aceptan la invitación de otro jugador.',
    '2021-11-5','Carreras','Windows, Xbox','forzahorizon5.jpg'
),
(
    'Lost Ark',
    'Lost Ark [a] es un juego de rol de acción en línea multijugador masivo (MMOARPG) de fantasía 2.5D de arriba hacia abajo[2] [3] Está co-desarrollado por Tripod Studio y la subsidiaria de desarrollo de juegos de Smilegate , Smilegate RPG . [4] Se lanzó por completo en la región de Corea del Sur el 4 de diciembre de 2019. [5] El juego también se lanzó en América del Norte , América del Sur y Europa el 11 de febrero de 2022, donde lo publica Amazon Games . [2] [6] [7] A las veinticuatro horas de su lanzamiento, se convirtió en el segundo juego más jugado en Steam . [8] [9]

Lost Ark ganó seis premios de juegos en varias categorías en los Korea Game Awards 2019. [10] Desarrollar el juego costó alrededor de $ 85,4 millones.',
    '2022-2-11','MMORPG, ROL','Windows','lostark.jpg'
),
(
    'Super Mario Odyssey',
    'Mario se enfrenta contra Bowser dentro de su nave. El villano ya estaba vestido y preparado para casarse con la Princesa Peach (a quien ya tenía secuestrada). Después de una fuerte pelea, Bowser le lanza su sombrero a Mario para tirarlo de la nave (el primer golpe sólo le tira la gorra a Mario, pero luego el sombrero regresa con efecto boomerang, y logra tirarlo de la nave). Después Bowser pisotea la gorra que se le había caído a Mario y se va del Reino Champiñón con la princesa, permitiendo que las hélices de su nave trituren la gorra. La escena termina con un pequeño alienígena con forma de sombrero atrapando un pedazo de la gorra que lleva la letra "M" de Mario, y mirando la nave de Bowser alejándose. Tras toda la aventura, Mario enfrenta a Bowser en plena boda. Cuando acaba la pelea, Bowser y Mario intentan seducir a Peach. La princesa los rechaza a los dos y activa la nave Oddysey. En el último momento Mario salta sobre Bowser, que se queda en la Luna. En una escena post créditos, la Roca Lunar (elemento en forma de cubo que se encuentra en algunos reinos, que durante el Modo Historia permanecía inerte) ubicada en el último reino comienza a emitir luces y a resonar.',
    '2017-10-27','Mundo Abierto','Nintendo Switch','supermarioodyssey.jpg'
),
(
    'Halo Infinite',
    'Halo Infinite es un videojuego de disparos en primera persona de la franquicia de videojuegos de ciencia ficción creada por Bungie Studios y actualmente desarrollada por 343 Industries. Es exclusivo para las plataformas Xbox One, Microsoft Windows y Xbox Series X|S. El juego es desarrollado por 343 Industries y distribuido por Xbox Game Studios. El juego es secuela de la historia de Halo 5: Guardians y Halo Wars 2 pero catalogado por 343 Industries como un reinicio espiritual para la saga Halo, o el inicio de una nueva era de Halo, se sabe que será un juego con inspiración de mundo abierto recordando a Halo CE que tenía un factor de exploración pero que en secuelas se fue volviendo más lineal.

El jefe Maestro el gran héroe de la humanidad y personaje principal de la saga se enfrentara a un grupo sanguinario y temible que alguna vez fueron parte del Covenant llamados los Desterrados, estos fueron integrados desde Halo Wars 2 y en las novelas del universo de Halo, ahora debutando como la amenaza principal en Halo Infinite.

Halo Infinite tiene muchas interrogantes que serán respondidas en la misma entrega con preguntas como: que paso con Cortana, como la UNSC parece estar perdiendo y que quieren los Desterrados en Zeta Halo. La entrega estrella de Xbox del 2021 Halo Infinite tendrá por primera vez un multijugador free to play en todas las plataformas en el que el juego sea lanzado, tendrá el conocido sistema de pase de batalla con temporadas siendo la primera anunciada hasta la fecha "héroes de Reach" que nos dará armaduras basadas en los personajes principales del juego Halo Reach entre otras recompensas.

Fue anunciado oficialmente el 10 de junio de 2018 durante la conferencia de Electronic Entertainment Expo 2018 con una demostración del nuevo motor del juego de nombre Slipspace Engine. Un año después, en la conferencia de Electronic Entertainment Expo 2019, se reveló un segundo adelanto estableciendo que la salida del juego será a finales del 2020 a la par de la nueva consola de Microsoft: la Xbox Series X|S. Sin embargo, el 11 de agosto de 2020, Microsoft anunció el retraso del videojuego para 2021 sin una fecha específica debido a la pandemia de coronavirus 2019-20.

Finalmente, el 25 de agosto de 2021 se confirmó la fecha de estreno para el 8 de diciembre de 2021.',
    '2021-12-8','Disparos en Primera Persona, Shooter','Xbox, Windows','halloinfinite.jpg'
)

GO